### ISSUE TITLE
Error when trying to replicate the example of `permetrics` Python library

### ISSUE THREAD

**Issue by davidechicco** [FelSiq/DBCV#8]
Hi FelSiq
Thanks for having released and for maintaining this DBCV Python package, it is very useful.
I'm writing here today because I tried to use your function on the toy example data used in the [documentation](https://permetrics.readthedocs.io/en/latest/pages/clustering/DBCVI.html) of the pypi `permetrics` package and I got an error.

Here's the piece of code:

```
import numpy as np
from dbcv import dbcv

# data matrix
data = np.array([[1, 2],  
                 [3, 4],
                 [5, 6],
                 [7, 8],
                 [9, 10]])

# labels array
labels = np.array([0, 0, 1, 1, 1])

# Calculate DBCV score
dbcv(X=data, y=labels)

```
And here's the log of the error:

> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/davide/miniconda3/lib/python3.11/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>                     ^^^^^^^^^^^^^^^^^^^
>   File "/home/davide/miniconda3/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/davide/my_projects/DBCV_R_package/dbcv_environment/lib/python3.11/site-packages/dbcv/core.py", line 106, in fn_density_sparseness
>     dsc = float(internal_edge_weights.max())
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/davide/my_projects/DBCV_R_package/dbcv_environment/lib/python3.11/site-packages/numpy/_core/_methods.py", line 45, in _amax
>     return umr_maximum(a, axis, None, out, keepdims, initial, where)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ValueError: zero-size array to reduction operation maximum which has no identity
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/davide/my_projects/DBCV_R_package/dbcv_environment/lib/python3.11/site-packages/dbcv/core.py", line 282, in dbcv
>     for cls_id, (dsc, internal_core_dists, internal_node_inds) in enumerate(ppool.starmap(fn_density_sparseness_, args)):
>                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/davide/miniconda3/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/davide/miniconda3/lib/python3.11/multiprocessing/pool.py", line 774, in get
>     raise self._value
> ValueError: zero-size array to reduction operation maximum which has no identity

Any idea on why this error happens?

Through the ClusteringMetric function of `permetrics`, I get 0.7083 as result:

```
import numpy as np
from permetrics import ClusteringMetric

## For integer labels or categorical labels
data = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y_pred = np.array([0, 0, 1, 1, 1])

cm = ClusteringMetric(X=data, y_pred=y_pred)

print(cm.density_based_clustering_validation_index())
print(cm.DBCVI())
```
I'm using Python 3.11.9 on Linux Xubuntu 22.

Muito obrigado,

-- Davide Chicco

**Comment by davidechicco** [comment]
Hi Felipe
Thanks for your reply and for your availability to investigate this aspect in the original MATLAB implementation.

For the record, I found out that using `labels = np.array([1, 2, 3, 4, 5])` rather than using the original labels (`[0, 0, 1, 1, 1]`) in that example makes the piece of code work, and its result is 0. I'm sharing this information with you in case it could be useful.

Best,

-- Davide Chicco

**Comment by FelSiq** [comment]
Hi, @davidechicco .

I pushed an updated to the main branch with a bugfix regarding this issue.

Please update your package version.

If the problem persists, or if you find any other issue, please let me know.

**Comment by davidechicco** [comment]
Hi @FelSiq
Thanks so much for your availability and your speed! It's so cool to see that you already fixed this issue! :-)

Just a curiosity now:  on that sample of data I posted originally, dbcv() of `permetrics` produces 0.7010073, while your dbcv() generates 0.9909929
Any idea on why the two results are different?

Best,

-- Davide

**Comment by FelSiq** [comment]
Hi, @davidechicco.

I'm glad you asked.

First, I must ask you once again to update your package version, since I found another edge case while investigating your question. In that regard, I apologize for the inconvenience.

---

My implementation follows exactly (or at least try to)  the specifications of the original MATLAB implementation. Now, there's two major factors that can affect the DBCV metric score even using an exactly replica of the original implementation:

1. The metric used to compute distances between points; in this case, the original MATLAB implementation and mine both use the *squared euclidean distance* as the default metric (this can be changed using the "metric" parameter);
2. The MST algorithm used in the implementation. Even though all MST algorithms produce connected components of same total weight, the internal node configuration can vary across distinct MSTs. Only internal nodes affect for the DBCV metric computation, hence the choice of MST algorithm matters. See #3 for an in-depth explanation.

I added some extra test files to compare the MATLAB implementation and mine, and both seems to produce the same results across some tests. In your toy data, the results for both implementation is (now) approximately 0.6942. If you use the standard euclidean distance as metric, the result in your toy data becomes approximately 0.4205 (both MATHLAB and mine).

*Which result is the correct one?* As far as I understand, *both*. The original paper doesn't prescribe a single, fixed metric that should be used for the DBCV calculation - even though they conducted all their experiments using the squared euclidean distance. So, as long as the chosen metric makes sense considering your data, and you keep the metric choice consistent across multiple clustering configurations in order to properly compare results, I don't see any problem in using other metrics.

Finally, it seems there's still a small difference in the result you reported using the permetrics package  - 0.7010073 - and my reported result in the same data following the original implementation - 0.6942. Admittedly, as long as my implementation is able to match the MATLAB implementation, this discrepancy doesn't concern me.

**Comment by davidechicco** [comment]
Hi @FelSiq 
Thanks so much for your availability and for your speed in fixing issues! That's a great job! You're doing a wonderful service for the community. I'm also going to mention @thieu1995 in case he wants to participate in this conversation.

I am totally convinced that your implementation and the original MATLAB's code are consistent: you explained the whole process here and in other messages. Fine.

I'm a bit more concerned, however, regarding the comparison between your package's behavior and `permetrics`'s behavior. On that example (0.701 versus 0.694), I consider those values the same, so no problem at all. But I found other cases where things are extremely different. 
I collected these additional examples in this [Python script I developed](https://gist.github.com/davidechicco/cf91c1679c819687b87ca0843d2869a2). Please download it and execute it on your computer.

You should be able to see something like this in output:

>  : : : : permetrics example : : : : 
> FelSiq/DBCV = 0.6942016978289678
> permetrics dbcvi = 0.7083333333333334
> 
>  : : : : Stack Overflow question example : : : : 
> FelSiq/DBCV = 0.9943128583104274
> permetrics dbcvi = 0.5210918734328118
> 
>  : : : : other example : : : : 
> FelSiq/DBCV = 0.9878553286128126
> permetrics dbcvi = 0.6985451280527727 
> 

The first results are produced on the example of `permetrics` already discussed in this issue, and again I consider them the same. The second case is based on an example provided by a user on Stack Overflow. The third case is an example prepared by a collaborator of mine.
In the last two cases, as you can see, the differences between your package's outcome and permetrics's outcome are huge.

I'm sharing this information with you in case you wanted to investigate these discrepancies further.

Thanks again for all the hard work!

-- Davide

**Comment by FelSiq** [comment]
Hi, @davidechicco.

The MATLAB code produces  0.9943128583104274 for the Stack Overflow example, thus matching the result from my code.

The third example, if I understood correctly, was randomly generated using no fixed pseudorandom seed, so I'm not able to reproduce your result.

I don't know why the permetrics results are different from my implementation.

----

If you're curious about the MATLAB results (code is available [here](https://github.com/pajaskowiak/dbcv)) and you don't have access to a MATLAB key, you can run the original implementation using the open-source [Octave](https://octave.org/) port using the following code:

_Setup: (terminal)_
```bash
git clone https://github.com/pajaskowiak/dbcv.git
cd dbcv/src
octave
```

**VERY IMPORTANT:** you can not use the ID 0 as a standard cluster ID using the MATLAB implementation because the label 0 is the noise label (even in the example files in the original repository the noise examples are incorrectly labeled as '-1' instead of '0'). You must update your cluster labels to something different than 0. So, your example will become:

_Example as a .txt file separated by whitespaces - labels are in the last column:_
```txt
1 1 1
1.2 1.1 1
0.8 1.2 1
4 4 2
4.2 4.1 2
3.8 4.2 2
```

_Executing DBCV on a dataset: (octave shell)_
```octave
pkg load statistics;
output_precision(16);

load ../data/dataset_1.txt;
val = dbcv(dataset_1(:, 1:2), dataset_1(:, 3))
```

---

Also, to ensure complete consistency across my implementation and the MATLAB implementation, please make sure to use both the "noise_id=0" and "use_original_mst_implementation=True" parameters as shown below (you don't have to use this setup on a regular basis, but it will make much easier to compare the results from both implementations).

```python
import dbcv

X = ...
y = ...

output = dbcv.dbcv(
    X=X,
    y=y,
    use_original_mst_implementation=True,
    metric="sqeuclidean",
    noise_id=0,
)
```

---

Finally, if you find any discrepancy between my implementation and the MATLAB one, please let me know, and I'll take a look into it as soon as possible.

Best regards,
Felipe.

**Comment by davidechicco** [comment]
Hi Felipe
Thanks for your extra steps and for your clarifications. If your implementation gets the same results of the MATLAB's original code, we can rest assured.

Best,

-- Davide
